# Generated by Django 4.2.9 on 2024-03-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
    ]
