# Generated by Django 4.2.9 on 2024-03-11 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0002_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="seller.color",
            ),
        ),
    ]
