# Generated by Django 4.2.9 on 2024-03-11 13:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0003_product_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="information",
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
