# Generated by Django 4.2.9 on 2024-03-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0006_orderitem_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="color",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Color",
        ),
    ]
