# Generated by Django 4.2.9 on 2024-03-26 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0007_alter_product_color_delete_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="user",
        ),
    ]
