# Generated by Django 4.2.9 on 2024-03-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0008_remove_product_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="image",
            field=models.ImageField(default=1, upload_to="photos2"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="price",
            field=models.CharField(default="exit", max_length=225),
            preserve_default=False,
        ),
    ]
