# Generated by Django 4.2.9 on 2024-04-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0009_orderitem_image_orderitem_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="status",
            field=models.IntegerField(
                choices=[
                    ("Pending", "Pending"),
                    ("On the way", "On the way"),
                    ("Delivered", "Delivered"),
                    ("Cancel", "Cancel"),
                    ("return", "return"),
                ],
                default=1,
            ),
        ),
    ]
