# Generated by Django 4.2.9 on 2024-04-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0010_alter_orderitem_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("On the way", "On the way"),
                    ("Delivered", "Delivered"),
                    ("Cancel", "Cancel"),
                    ("return", "return"),
                ],
                default=1,
                max_length=225,
            ),
        ),
    ]
