# Generated by Django 4.2.9 on 2024-04-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0015_orderitem_final"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=225)),
            ],
        ),
    ]
