# Generated by Django 4.2.9 on 2024-04-21 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0016_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="color",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="seller.color"
            ),
        ),
    ]
